### ISSUE TITLE
IOError: Could not open stream.

### ISSUE THREAD

**Issue by vaibhawc** [JuliaML/MLDatasets.jl#46]
I am beginner to Julia.
Gettting this with `MNIST.traindata()`

**Comment by vaibhawc** [comment]
I don't understand why it was coming. I got frustrated, I saw on terminal that a y/n question about downloading dataset was being asked. I already had the dataset at another folder (I keep tinkering with MNIST a lot) so I copied to .julia/datadeps/MNIST/.. now things work. I am using Pluto. Not sure if this has to do with Pluto.

**Comment by zuckberj** [comment]
I'm having the same problem here with Pluto, but directly with DataDeps.jl
The problem is that Pluto doesn't support input to the "terminal", my workaround was to set the environment variable DATADEPS_ALWAYS_ACCEPT to true

[Reference](https://www.oxinabox.net/DataDeps.jl/v0.5/z40-apiref.html#Base.download-Tuple{DataDep,Any})

You can achieve that by modifying or creating the file on `~/.julia/config/startup.jl` with `ENV["DATADEPS_ALWAYS_ACCEPT"] = true`

**Comment by FelixBenning** [comment]
If you have this problem with Pluto, an alternative to setting the environment variable as suggested by @zuckberj, is to use
`MNIST.download(i_accept_the_terms_of_use=true)` first. This downloads the data without the promt allowing you to use `MNIST.traindata()` afterwards without issue.
