### ISSUE TITLE
[Quetion] Why are the image matrices transposed?

### ISSUE THREAD

**Issue by eliascarv** [JuliaML/MLDatasets.jl#62]
Hi, I'm a beginner in ML and I was studying Flux.jl using the MNIST image dataset.
However, I realized that the images in MLDatasets were transposed, but in Flux, which is Deprecated, aren't transposed.

![IMG_20210516_141023_039](https://user-images.githubusercontent.com/73039601/118406073-3d2e9000-b651-11eb-9779-99a127112038.jpg)

![IMG_20210516_141025_397](https://user-images.githubusercontent.com/73039601/118406314-ebd2d080-b651-11eb-9bca-d8cc838d0bd9.jpg)

![IMG_20210516_141027_800](https://user-images.githubusercontent.com/73039601/118406323-f42b0b80-b651-11eb-871c-f8bdaa137f0d.jpg)

![IMG_20210516_141031_319](https://user-images.githubusercontent.com/73039601/118406328-fb521980-b651-11eb-960d-45139e6d5db4.jpg)

Is there any reason for the images to be transposed in MLDatasets?

**Comment by johnnychen94** [comment]
This is an issue related to its memory layout.

In Julia, native array types use column-major order, so the first dimension is height, and the second dimension is width. In Python, native array types use row-major order, so the first dimension is width, and the second dimension is height.

MLDatasets simply reads the data without any dimension permutation, so you'll observe the "rotation" when you try to display the image. This is because MNIST data is originally written in a row-major order format.

As long as your data uses the same layout, whether it is transposed or not, it won't make a difference when you train a network on it.

**Comment by eliascarv** [comment]
Thanks for the answer. It was just a doubt that I had.
